.build_image: &build_image
  - docker build . -t ${DOCKER_IMAGE}:${APP_VERSION} -t ${DOCKER_IMAGE}:latest --build-arg APP_VERSION=${APP_VERSION}
  - docker push ${DOCKER_IMAGE}:latest
  - docker push ${DOCKER_IMAGE}:${APP_VERSION}
  - curl -X GET -u ${DOCKER_REGISTRY_USER}:${DOCKER_REGISTRY_PASS} https://${DOCKER_REGISTRY_HOST}/v2/tpone_backend/tags/list
before_script:
  - export APP_VERSION=$(echo $CI_COMMIT_REF_NAME | cut -d '-' -f 2)
  - export DOCKER_IMAGE="${DOCKER_REGISTRY_HOST}/tpone_backend"
  - docker login -u ${DOCKER_REGISTRY_USER} -p ${DOCKER_REGISTRY_PASS} ${DOCKER_REGISTRY_HOST}

stages:
  - buildImage
buildImage:
  stage: buildImage
  only:
    refs:
      - /deploy-*/
  script: *build_image
